USE `myidea`;

DROP TABLE IF EXISTS `USER`;
DROP TABLE IF EXISTS `IDEA`;
DROP TABLE IF EXISTS `ROLE`;
DROP TABLE IF EXISTS `USER_ROLE`;
DROP TABLE IF EXISTS `TAG`;
DROP TABLE IF EXISTS `IDEA_TAG`;
DROP TABLE IF EXISTS `IDEA_LIKES`;
DROP TABLE IF EXISTS `COMMENT`;
DROP TABLE IF EXISTS `COMMENT_LIKES`;
DROP TABLE IF EXISTS `UserConnection`;